name: CI Pipeline MLOps

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'

jobs:
  # STAGE 1 : Entraînement (Exécuté pour feature/* et develop)
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install scikit-learn joblib fastapi uvicorn

      - name: Train model
        run: python app/training_model.py

  # STAGE 2 : Docker (Uniquement pour develop)
  docker-workflow:
    needs: train
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions: # Obligatoire pour écrire dans GitHub Packages
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # STEP 1 : Construction
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/mlops-iris:latest .

      # STEP 2 : Publication
      - name: Publish Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/mlops-iris:latest