name: CI Pipeline MLOps

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'

jobs:
  # JOB 1 : Toujours exécuté (Entraînement)
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies 
        run: |
          pip install scikit-learn joblib
          
      - name: Train model
        run: python app/training_model.py

  # JOB 2 : Uniquement pour la branche develop (Build & Publish Docker)
  docker-workflow:
    needs: train
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push to GitHub Container Registry (tags: latest + sha)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/mlops-iris:latest
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/mlops-iris:${{ github.sha }}
